component_depth: 1
languages:
- java
exclude:
- ./bin/.*
- ./bin/megamek/.*
- ./bin/megamek/client/.*
- ./bin/megamek/client/bot/.*
- ./bin/megamek/client/bot/ga/.*
- ./bin/megamek/client/bot/ui/.*
- ./bin/megamek/client/bot/ui/AWT/.*
- ./bin/megamek/client/bot/ui/swing/.*
- ./bin/megamek/client/commands/.*
- ./bin/megamek/client/event/.*
- ./bin/megamek/client/ui/.*
- ./bin/megamek/client/ui/AWT/.*
- ./bin/megamek/client/ui/AWT/boardview3d/.*
- ./bin/megamek/client/ui/AWT/util/.*
- ./bin/megamek/client/ui/AWT/widget/.*
- ./bin/megamek/client/ui/swing/.*
- ./bin/megamek/client/ui/swing/util/.*
- ./bin/megamek/client/ui/swing/widget/.*
- ./bin/megamek/common/.*
- ./bin/megamek/common/actions/.*
- ./bin/megamek/common/containers/.*
- ./bin/megamek/common/event/.*
- ./bin/megamek/common/loaders/.*
- ./bin/megamek/common/net/.*
- ./bin/megamek/common/net/marshall/.*
- ./bin/megamek/common/options/.*
- ./bin/megamek/common/preference/.*
- ./bin/megamek/common/util/.*
- ./bin/megamek/common/verifier/.*
- ./bin/megamek/common/weapons/.*
- ./bin/megamek/common/weapons/infantry/.*
- ./bin/megamek/common/xml/.*
- ./bin/megamek/server/.*
- ./bin/megamek/server/commands/.*
- ./bin/megamek/server/victory/.*
- ./bin/megamek/test/.*
- ./bin/megamek/test/client/.*
- ./bin/megamek/test/entities/.*
- ./bin/megamek/test/xml/.*
- ./data/.*
- ./data/boards/.*
- ./data/boards/buildings/.*
- ./data/boards/scenarios/.*
- ./data/boards/solaris/.*
- ./data/boards/unofficial/.*
- ./data/images/.*
- ./data/images/camo/.*
- ./data/images/hexes/.*
- ./data/images/hexes/boring/.*
- ./data/images/hexes/bridge/.*
- ./data/images/hexes/fluff/.*
- ./data/images/hexes/grass/.*
- ./data/images/hexes/hardened/.*
- ./data/images/hexes/heavy/.*
- ./data/images/hexes/isometric/.*
- ./data/images/hexes/isometric/trees/.*
- ./data/images/hexes/jungle/.*
- ./data/images/hexes/light/.*
- ./data/images/hexes/limbs/.*
- ./data/images/hexes/lunar/.*
- ./data/images/hexes/magma/.*
- ./data/images/hexes/mars/.*
- ./data/images/hexes/megaart/.*
- ./data/images/hexes/mud/.*
- ./data/images/hexes/sand/.*
- ./data/images/hexes/singlehex/.*
- ./data/images/hexes/snow/.*
- ./data/images/hexes/swamp/.*
- ./data/images/hexes/transparent/.*
- ./data/images/hexes/tundra/.*
- ./data/images/misc/.*
- ./data/images/portraits/.*
- ./data/images/units/.*
- ./data/images/units/battle armor/.*
- ./data/images/units/mechs/.*
- ./data/images/units/unused/.*
- ./data/images/units/vehicles/.*
- ./data/images/units/warships/.*
- ./data/images/units/wrecks/.*
- ./data/images/widgets/.*
- ./data/mechfiles/.*
- ./data/mechfiles/ge/.*
- ./data/mechfiles/infantry/.*
- ./data/mechfiles/infantry/Clan Infantry/.*
- ./data/mechfiles/infantry/IS Infantry/.*
- ./data/mechfiles/unsupported/.*
- ./data/mechfiles/unsupported/infantry/.*
- ./data/mechfiles/unsupported/infantry/Clan Infantry/.*
- ./data/mechfiles/unsupported/infantry/Inner Sphere Infantry/.*
- ./data/mechfiles/unsupported/mechs/.*
- ./data/mechfiles/unsupported/mechs/3025 IS/.*
- ./data/mechfiles/unsupported/mechs/3055 IS/.*
- ./data/mechfiles/unsupported/vehicles/.*
- ./data/scenarios/.*
- ./data/scenarios/1stSomersetStrikers/.*
- ./data/scenarios/LawyersGunsAndMoney/.*
- ./data/scenarios/MonteDiablo/.*
- ./data/scenarios/Northwind Highlanders/.*
- ./data/scenarios/TheGreatRefusal/.*
- ./data/scenarios/TrainingScenarios/.*
- ./data/sounds/.*
- ./docs/.*
- ./l10n/.*
- ./l10n/megamek/.*
- ./l10n/megamek/client/.*
- ./l10n/megamek/client/bot/.*
- ./l10n/megamek/common/.*
- ./l10n/megamek/common/options/.*
- ./lib/.*
- ./logs/.*
- ./mmconf/.*
- ./packaging_utils/.*
- ./packaging_utils/launch4j/.*
- ./packaging_utils/launch4j/bin/.*
- ./packaging_utils/launch4j/head/.*
- ./packaging_utils/launch4j/lib/.*
- ./packaging_utils/launch4j/manifest/.*
- ./packaging_utils/launch4j/w32api/.*
- ./packaging_utils/launch4j/web/.*
